spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/fangio_db}
spring.datasource.name=${DB_NAME:fangio_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:rootpassword}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

app.jwt.secret=${JWT_SECRET:VGhpcy1pcy1hLXZlcnktc2VjdXJlLWtleS1mb3Itand0LWluLXByb2R1Y3Rpb24tYXBw}
app.jwt.expiration-miliseconds=${JWT_EXPIRATION: 86400000}

admin.setup.username=${SUPER_ADMIN_USERNAME:admin}
admin.setup.password=${SUPER_ADMIN_PASSWORD:admin123}
admin.setup.email=${SUPER_ADMIN_EMAIL:admin@fangio.local}