name: Despliegue a Produccion Fangio

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Conectar al VPS por SSH y actualizar contenedores
   
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            
            cd /home/ubuntu/fangio-vehiculos
            
           
            git pull origin main
            
           
            docker compose up -d --build